# -*- coding: utf-8 -*-
"""Movie Recomendation System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBO1IIYZk2g4xRMUorIUKEf14x81acp4
"""

import requests
from textblob import TextBlob

# 🔑 Replace with your actual TMDB API key
TMDB_API_KEY = '14951b2d136185491c5a8f1662f9f254'

# --------------------------
# 1. Fetch Movie Details from TMDB
# --------------------------
def get_tmdb_movie_details(movie_name):
    search_url = "https://api.themoviedb.org/3/search/movie"
    search_params = {
        'api_key': TMDB_API_KEY,
        'query': movie_name
    }

    response = requests.get(search_url, params=search_params)
    data = response.json()

    if not data['results']:
        print("❌ Movie not found in TMDB.")
        return None, None

    movie = data['results'][0]
    movie_id = movie['id']

    # Fetch detailed info
    details_url = f"https://api.themoviedb.org/3/movie/{movie_id}"
    details_params = {'api_key': TMDB_API_KEY}
    detail_response = requests.get(details_url, params=details_params)
    details = detail_response.json()

    genres = ", ".join([genre['name'] for genre in details.get('genres', [])])
    print("\n🎬 Movie Details:")
    print(f"Title       : {details.get('title')}")
    print(f"Release Date: {details.get('release_date')}")
    print(f"Genres      : {genres}")
    print(f"Rating      : {details.get('vote_average')}")
    print(f"Overview    : {details.get('overview')}")
    print(f"Poster URL  : https://image.tmdb.org/t/p/w500{details.get('poster_path')}\n")

    return movie_id, details.get('title')

# --------------------------
# 2. Get Similar Movies from TMDB
# --------------------------
def get_similar_movies(movie_id, top_n=5):
    similar_url = f"https://api.themoviedb.org/3/movie/{movie_id}/similar"
    params = {'api_key': TMDB_API_KEY}
    response = requests.get(similar_url, params=params)
    data = response.json()

    results = data.get('results', [])
    if not results:
        print("⚠️ No similar movies found.")
        return

    print("🎯 Similar Movies Recommended:")
    for movie in results[:top_n]:
        print(f"→ {movie['title']} (Rating: {movie['vote_average']})")

# --------------------------
# 3. Mock Reviews and Sentiment Analysis
# --------------------------
def get_mock_reviews():
    return [
        "The movie was absolutely stunning and emotional.",
        "I did not enjoy it. It was too slow and boring.",
        "Great performances by the actors!",
        "Not worth the hype in my opinion.",
        "Loved the visuals and background music."
    ]

def analyze_reviews(reviews):
    print("\n💬 Sentiment Analysis:")
    for review in reviews:
        blob = TextBlob(review)
        sentiment = "Positive" if blob.sentiment.polarity >= 0 else "Negative"
        print(f"Review: {review}")
        print(f"→ Sentiment: {sentiment}\n")

# --------------------------
# 4. Main Application Loop
# --------------------------
if __name__ == "__main__":
    print("🎥 Welcome to the TMDB Movie Recommender\n")

    while True:
        movie_name = input("🎞️ Enter a movie name or type 'exit': ").strip()
        if movie_name.lower() == 'exit':
            print("👋 Goodbye!")
            break

        movie_id, title = get_tmdb_movie_details(movie_name)

        if movie_id:
            get_similar_movies(movie_id)
            print("\n📝 Analyzing Mock Reviews...")
            reviews = get_mock_reviews()
            analyze_reviews(reviews)

